apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  USERNAME: {{ .Values.secrets.username.value | b64enc }}
  PASSWORD: {{ .Values.secrets.password.value | b64enc }}
  THEBIGSECRET: {{ .Values.secrets.thebigsecret.value | b64enc }}
